### PR TITLE
Added TravisCI integration to the Demo

### PR DESCRIPTION
**Pull request by colemanjackson**
With this Commit, we now ensure every new PR opened against the demo application master will have a CI Deploy test run against that commit. 

The test simply deploys stage 3 of the demo to start, will add further deployments of step 1 and 2 in the coming days. 

build breakdown:
travis.yml -> calls deploy_rollup.sh
deploy_rollup -> installs bx (install_bx.sh), logs into bluemix (bx_login.sh) and deploys the watson talk service (deploy.sh)

### CODE REVIEW

**Comment by jgarcows** [comment]
You accidentally put your namespace in place of <namespace> on the Stage3 deployment yml.

**Comment by jgarcows** [comment]
We shouldn't use bluemix passwords for the travis CI integration.  We and should instead use bluemix api keys.  An API key can be made using: `bx iam api-key-create ` and then passed into bx login using `--apikey <value>`.

**Comment by jgarcows** [comment]
Here's the code I used in the past to do api key

```
if [ -n "$BX_API_KEY" ]; then
    bx login -a https://${BLUEMIX_API_HOST} -o ${CF_ORG} -s ${CF_SPACE} --apikey ${BX_API_KEY}
else
    echo "BX_API_KEY secret environment variable MUST be set to perform needed bx login"
    echo "Create a bx api key using bx iam api-key-create for the org/space you are targeting"
fi
```

**Comment by colemanjackson** [comment]
I'm fine with changing my approach if necessary, but why no bluemix passwords? Travis specifically encrypts the environment variables I use and masks them in the logs. Security-wise, we should be good. @jgarcows

**Comment by jgarcows** [comment]
A handful of reasons:
1) It is a weakness if travis gets hacked, since they have to be able to unencrypt it to use it.
2) Right now, any github user could fork our repo and make a pull request that has malicious code in it that will send them your password in plaintext.  We don't even have to approve the pull request, just having it exist is enough to kick off the travis build where something as simple as a single curl post with your password will do it.
3) Since this is a demo, we should show best practices, so even if we trust everything, it is still good to show any users how to do the API key.
4) It is good to test the Kube service with an API key login.  Since none of us use API keys in normal day-to-day work, it will give us better coverage to use it in our automated tests.

**Review by jgarcows — DISMISSED** [review]
Stage3/README.md and Stage3/watson-deployment.yml can't have hard coded namespaces in it.  In deploy.sh, we should use sed to replace <namespace> in the yml file.

**Comment by colemanjackson** [comment]
LGTM, pending approval from TravisCI

**Pull request merged**
