### PR TITLE
Bhpratt alpine

### PR DESCRIPTION
**Pull request by bhpratt**
ibmnode is being removed from the container registry on Friday 1/19.

upon testing, dockerhub/node is over 500mb memory (which exceeds the free registry quota).

so using alpine, a much slimmed down version. I've tested to confirm that it works in Labs 1, 2, and 3.

### CODE REVIEW

**Comment by bhpratt** [comment]
Note: I didn't update stage 1, 2, or 3. I'm not sure if those folders are meant to be in this repo?

**Comment by bhpratt** [comment]
@kennjason I tagged you since ibmnode is getting removed from the registry today. That will break parts of this tutorial, unfortunately.

**Comment by jkomg** [comment]
@bhpratt ouch, this is a setback.

**Comment by jkomg** [comment]
@bhpratt so you've uploaded an alpine image and it's working for the first 3 labs? Will you be able to test the rest?

**Comment by bhpratt** [comment]
@kennjason Labs 4, 5, and 6 don't use the ibmnode dockerfile, so no changes needed there.

I didn't update stage 1, 2, and 3 because I wasn't sure what they were.

**Comment by jkomg** [comment]
@bhpratt those directories were added as a part of #43

**Comment by bhpratt** [comment]
@kennjason Interesting, thanks. It appears that the stage folders are duplicative of the Lab folders?

For example, everything in stage2 also is included in Lab 2 (including the healthcheck.yml and the description of scaling up and down). Should the stage folders just be removed?

**Comment by jkomg** [comment]
We should check to see if the readme files themselves all consistently contain references to one folder or another and just go with that if it's duplicate. @bhpratt

**Comment by bhpratt** [comment]
Ok, I'll open a different PR for that one.

**Review by jkomg — APPROVED** [review]
lgtm

**Comment by jkomg** [comment]
We'll want an official alpine image uploaded to the IBM image repo

**Pull request merged**
