### PR TITLE
fix the broken IBM Cloud CLI link, and change bluemix to ibm cloud

### PR DESCRIPTION
**Pull request by hintcnuie**
fix the broken IBM Cloud CLI link, and change the wording of bluemix to IBM Cloud

## What Does this Pull request do?

1. The previous IBM Cloud CLI linkage is broken.
 
   The link in the readme is https://cloud.ibm.com/docs/cli?topic=cloud-cli-ibmcloud-cli
,  but it is broken now.
cloud-cli-ibmcloud-cli

2 Add description for the IBM Cloud ClI , after the CLI installation,  several Plugins are installed by default.
IBM_Cloud_CLI_installation

2. Change the wording from IBM to Cloud
   Change the wording from IBM to Cloud, since Bluemix has changed to IBM Cloud.

## Provide context of why this work is happening

After I follow the Lab document, I notice these issues. IBM Cloud is growing very fast, and the CLI installation might be changed and not updated yet in this Lab material.

## How Has This Been Tested?

Follow the Lab 0 material and find it's wrong to install IBM CLI

Install the new IBM CLI in a separated RHEL 7.7 and verified.
IBM_Cloud_CLI_installation

Screen Shot 2020-01-09 at 12 12 27 PM

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] No zip files
- [X] Files are in the proper directories
- [X] This work is ready to be merged

### CODE REVIEW

**Comment by hintcnuie** [comment]
@jgarcows please help to review, thanks!

**Comment by jgarcows** [comment]
I don't like the large install footprint using the link you suggest.  I think we should use this link instead:

https://cloud.ibm.com/docs/cli?topic=cloud-cli-install-ibmcloud-cli

Which just installs the ibmcloud CLI, then we have directions for the plugins needed within the readme

**Comment by hintcnuie** [comment]
I agree to your idea, from the directions for plugin section,  it is better to install the standalone version, otherwise there is no needed for the plugin installation.

but another thing to be considered , is to consider the time to download the standalone CLI.  the overall size is 18M currently,   and it takes me 16 minutes,  though I am in the home  without any VPN , using China Unicom network. It might take more time for some other countries .

standalone

**Comment by hintcnuie** [comment]
Omm,  I checked the CLI with Dev tools, it also takes a lot of time from my home network, so agree with you,  another commit is delivered, pls help to check thanks!

**Comment by hintcnuie** [comment]
@jgarcows please help to review, thanks!

**Review by jgarcows — APPROVED** [review]

**Pull request merged**
