### PR TITLE
Bhpratt stageremoval

### PR DESCRIPTION
**Pull request by bhpratt**
Removing stage content. Duplicates Labs 1, 2, and 3.

### CODE REVIEW

**Comment by jkomg** [comment]
@bhpratt do you think it's valuable to remove the explicit linking to each lab? Why?

**Comment by bhpratt** [comment]
@kennjason I didn't see this comment. It's removing links to the stage1 files which are duplicates of what exists in the labs.

**Review by jkomg — APPROVED** [review]
this lgtm, but it's got some conflicts that must be resolved before we can merge

**Comment by bhpratt** [comment]
Ok, I think the merge conflicts have been fixed.

**Pull request merged**
